name: CI
on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'

      - name: Checkout OneSignal-Flutter-SDK
        uses: actions/checkout@v3

      - name: Install Dependencies 🔗⛓📦
        run: flutter pub get

      - name: Static Analysis
        run: flutter analyze

      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .

      - name: Run Flutter unit tests
        run: flutter test
